### ISSUE TITLE
Page archetype

### ISSUE THREAD

**Issue by ebouchut** [kakawait/hugo-tranquilpeak-theme#106]
I would like to have a  *`page` archetype* with at least the following in the front matter:
```yaml
comments:       false

showDate:       false

showSocial:     false
showTags:       false
showPagination: false
```
This would be useful for non blog pages like _Contact_ and _About_ for instance.

I plan on creating a PR with both the `page`archetype and with the `showDate` param that does not exist today.

### Configuration

 - **Hugo version**: 0.18.1
 - **Tranquilpeak version**:  0.2.1-ALPHA
 
### Actual behavior

`hugo new page/about.md`
creates a page  **with** the *date*, social buttons, tags and pagination.

### Expected behavior

`hugo new page/about.md`
creates the page  **without** the **date**, social buttons, tags and pagination.
