### ISSUE TITLE
highlight

### ISSUE THREAD

**Issue by jankeyfu** [kakawait/hugo-tranquilpeak-theme#316]

**Comment by jankeyfu** [comment]
Configuration
maxos :
Chrome 71:
Hugo version - 0.52:
Tranquilpeak version- 0.4.3-BETA:

I use markdown code block ,but it don't highlight in any language tag. 

code 
![image](https://user-images.githubusercontent.com/19988523/50370102-6d39ec00-05db-11e9-916b-35cb1160829f.png)


<code class="language-php codeblock hljs">$a = $b + $c;
</code>

**Comment by kakawait** [comment]
Could you please provide a markdown sample to reproduce?

**Comment by tlex** [comment]
I have the same problem as seen [on this page](https://alex.thom.ae/2016/05/26/automated-website-provisioning/).

The code used for the first block is the same that generates this block:
```yaml
pillar_source_merging_strategy: recurse
file_roots:
  base:
    - /srv/salt
    - /srv/salt/filebase

fileserver_backend:
  - roots

pillar_roots:
  base:
    - /srv/pillars
```

While here on github it works (three back-ticks followed by `yaml`), it doesn't work on my installation.

The generated DOM element looks good, there just isn't any highlighting:
```html
<code class="language-yaml codeblock">pillar_source_merging_strategy: recurse
file_roots:
  base:
    - /srv/salt
    - /srv/salt/filebase

fileserver_backend:
  - roots

pillar_roots:
  base:
    - /srv/pillars
</code>
```
