### ISSUE TITLE
Travis CI to deploy https://tranquilpeak.kakawait.com based on exampleSite

### ISSUE THREAD

**Issue by kakawait** [kakawait/hugo-tranquilpeak-theme#35]

**Comment by willwade** [comment]
I now use Netlify - its free for Open Source projects like tranquil peak and its amazingly simple. A lot less simple than the travis approach. Take a read of https://www.netlify.com/blog/2015/07/30/hosting-hugo-on-netlifyinsanely-fast-deploys/ 

to deploy the example site I guess the deploy command would be:

`mv exampleSite/* ./ && hugo_0.19`

done!

(NB: Im not sure the path that it uses - that first part may have to change. NB2: You have to use hugo 0.19 - its default is 0.17 from memory and that crashes on tranquil peak).

**Comment by kakawait** [comment]
Yes can be a great alternative to Travis. I will read that. Even more I heard smashing magazine is using Netlify

**Comment by chuyskywalker** [comment]
The `.travis.yml` is actually quite terse:

```
script:
  # Cleans out any possible old public directories -- just to be sure
  - rm -rf public || exit 0
  # Builds the site into the public dir
  - ./binaries/hugo -s site/ -d ../public

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
```

I followed [this brief tutorial](https://www.metachris.com/2017/04/continuous-deployment-hugo---travis-ci--github-pages/) and cleaned up the above from there.
