### ISSUE TITLE
How to justify each blogpost content?

### ISSUE THREAD

**Issue by konradsemsch** [kakawait/hugo-tranquilpeak-theme#370]
I'm looking for a similar reference as here: [link](https://github.com/gcushen/hugo-academic/issues/499) - how can I globally set each blogpost text to be justified/ centered? I was going through the entire user guide and couldn't find anything about that.

**Comment by juba** [comment]
A bit of CSS in a custom CSS file should do the trick, something like :

```css
#main .post-content {
  text-align: justify;
}
```
