### ISSUE TITLE
Possibility to override Permalink

### ISSUE THREAD

**Issue by kvaps** [kakawait/hugo-tranquilpeak-theme#375]
Hi, original theme from hexo was support to override `Continue reading` with external link, eg:

```yaml
---
title: Hexo website
date: 2012-04-12 23:33:26
link: http://www.hexo.io/
categories:
- tranquilpeak
- features
thumbnailImagePosition: left
thumbnailImage: http://d1u9biwaxjngwg.cloudfront.net/hexo-website/peak-140.jpg
---
This is a link post. Clicking on the link should open [Hexo](http://www.hexo.io/) in a new tab or window.
<!-- more -->
```

Will be translated to:
![image](https://user-images.githubusercontent.com/7556217/63475707-573c3e00-c47e-11e9-98b7-9d51d9a38df1.png)

Where title, and `Go to website` link refers to http://www.hexo.io/

Is there any option to achieve the same beh in hugo?
