### ISSUE TITLE
customJS with array seems not work

### ISSUE THREAD

**Issue by justforuse** [kakawait/hugo-tranquilpeak-theme#398]
### Configuration

 - **Operating system with its version**: 
 - **Browser with its version**:
 - **Hugo version**: 
 - **Tranquilpeak version**: 
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**:
 

### Actual behavior

As said, we can import js file, but I need import two files, so I write this:

```
  # Custom JS. Put here your custom JS files. They are loaded after the theme JS;
  # they have to be referred from static root. Example
  [[params.customJS]]
    src = [
      "https://unpkg.com/react@16/umd/react.production.min.js",
      "https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"
    ]

```

Array not work, and no errors in terminal, but single file works fine.

### Steps to reproduce the behavior

Do I write wrong code? have someone tried like this? thanks your advice.

**Comment by kakawait** [comment]
Could you please try with following syntax

```toml
[[params.customJS]]
    src = "https://unpkg.com/react@16/umd/react.production.min.js"
[[params.customJS]]
    src = "https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"
```
