### ISSUE TITLE
Highlight style not taking effect

### ISSUE THREAD

**Issue by VivekRagunathan** [kakawait/hugo-tranquilpeak-theme#452]
### Configuration

 - **Operating system with its version**: Mac Catalina 10.15.6
 - **Browser with its version**: Brave / Chrome Latest
 - **Hugo version**:  **`0.74.3`**
 - **Tranquilpeak version**: **`0.4.8-BETA`**
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: No, on local
 
### Actual behavior

I am trying to change the code highlight style from default to `solarized.dark` (or `zenburn`), and I have this in my `config.toml`:

```toml
[markup]
  [markup.highlight]
    style = "solarized.dark"
    codeFences = false # I added based on a discussion in the hugo discourse. But no effect either way!
```

The code blocks do not use the style configured above but the default.

### Expected behavior

The code blocks do not use the style configured in the `config.toml` but the default.
