### ISSUE TITLE
global config key thumbnailImagePosition is not used

### ISSUE THREAD

**Issue by kakawait** [kakawait/hugo-tranquilpeak-theme#73]
```toml
[params]
    thumbnailImagePosition = "bottom"
```

is never used
